site/config/routes.rb
RedHatCloud::Application.routes.draw do

  scope Rails.configuration.app_scope do

    match 'getting_started/express', :to => redirect('/app/express')
    match 'getting_started/flex', :to => redirect('/app/flex')
    match 'access/express(/:request)', :to => redirect('/app/express')
    match 'access/flex(/:request)', :to => redirect('/app/flex')

    match 'getting_started' => 'getting_started/generic#show'
    match 'getting_started_external/:registration_referrer' => 'getting_started_external#show'
    match 'email_confirm' => 'email_confirm#confirm'
    match 'email_confirm_external/:registration_referrer' => 'email_confirm#confirm_external'
    match 'email_confirm_flex' => 'email_confirm#confirm_flex'
    match 'email_confirm_express' => 'email_confirm#confirm_express'
    match 'express' => 'product#express', :as => 'express'
    match 'flex' => 'product#flex', :as => 'flex'
    match 'express_protected' => 'product#express_protected', :as => 'express_protected'
    match 'flex_protected' => 'product#flex_protected', :as => 'flex_protected'
    match 'power' => 'product#power', :as => 'power'
    match 'flex_redirect' => 'product#flex_redirect', :as => 'flex_redirect'
    match 'about' => 'home#about', :as => 'about'
    match 'twitter_latest_tweet' => 'twitter#latest_tweet'
    match 'twitter_latest_retweets' => 'twitter#latest_retweets'
    match 'partners/join' => 'partner#join', :as=> 'join_partner'

    resource :user,
             :controller => "user",
             :as => "web_users",
             :only => [:new, :create]

    match 'user/new/flex' => 'user#new_flex', :via => [:get]
    match 'user/new/express' => 'user#new_express', :via => [:get]
    get 'user' => 'user#new'
    match 'user/create/external' => 'user#create_external', :via => [:post]

    resource :terms,
             :as => "terms",
             :controller => "terms",
             :path_names => { :new => 'accept' },
             :only => [:new, :create]

    match 'legal/acceptance_terms' => 'terms#acceptance_terms', :as => 'acceptance_terms'

    match 'video/:name' => 'video#show', :as => 'video'

    match 'legal' => 'legal#show'
    match 'legal/site_terms' => 'legal#site_terms'
    match 'legal/services_agreement' => 'legal#services_agreement'
    match 'legal/acceptable_use' => 'legal#acceptable_use'
    match 'legal/openshift_privacy' => 'legal#openshift_privacy'

    resource :login,
             :controller => "login",
             :only => [:show, :create]
    match 'login/error' => 'login#error', :via => [:get]
    match 'login/flex' => 'login#show_flex', :via => [:get]
    match 'login/express' => 'login#show_express', :via => [:get]

    resource :logout,
             :controller => "logout",
             :only => [:show]
    match 'logout/flex' => 'logout#show_flex', :via => [:get]
    match 'logout/express' => 'logout#show_express', :via => [:get]

    resources :partners,
              :controller => "partner",
              :only => [:show, :index]

    resource :express_domain,
             :controller => "express_domain",
             :as => "express_domains",
             :only => [:new, :create]
  
    resource  :express_app,
              :controller => "express_app",
              :as => "express_apps",
              :only => [:new, :create]
    
    get 'express_app/health_check' => 'express_app#health_check'
    
    match 'control_panel' => 'control_panel#index'
    match 'dashboard' => 'control_panel#index', :as => 'dashboard'

    root :to => "home#index"

  end
end

site/app/controllers/product_controller.rb
require 'uri'

class ProductController < ApplicationController

  def express
    # Handle the email confirmation flow
    @product = 'express'
    
    if session[:confirm_flow]
      session.delete(:confirm_flow)
      flash[:notice] = "Almost there!  Login to complete your registration."
      require_login and return
    end
  end
  
  def flex_redirect
    redirect_to '/flex' and return
  end
  
  def flex
    @product = 'flex'
    
    # Handle the email confirmation flow
    if session[:confirm_flow]
      session.delete(:confirm_flow)
      flash[:notice] = "Almost there!  Login to complete your registration."
      require_login and return
    elsif workflow_redirect
      # Handles flex redirecting back to /app/flex
      return
    end
  end

  def power
    @product = 'power'
  end
end

site/app/helpers/product_helper.rb
module ProductHelper
end

site/app/views/product/flex.html.haml
-# file: Flex product page

= render 'layouts/flashes'

- content_for :page_title do
  Flex

-# Product navigation
- content_for :product_nav do
  %ul 
    %li
      = link_to "What's Flex?", '#about', :class => 'active'
    %li
      = link_to 'Videos', '#videos'
    %li
      = link_to 'Documentation', 'http://docs.redhat.com/docs/en-US/OpenShift_Flex/1.0/html/User_Guide/index.html'
    %li
      = link_to 'Forum', 'http://www.redhat.com/openshift/forums/flex'
  
  - if logged_in?
    - if has_access? :express
      #account.signed_in
        %header
          %h2
            Account
        
        %ul
          %li
            = link_to 'Quickstart', '#quickstart'
          %li
            = link_to 'Flex Console', '/flex'
    
    - else
      #account.signed_out
        %header
          %h2
            Account
        
        %ul
          %li
            Access Pending...
            
  - else
    #account.signed_out
      %header
        %h2
          Account
      %ul  
        %li
          = link_to 'Sign up to try Flex!', '/app/user/new/flex', :class => 'sign_up'

-# Main Content
- content_for :product_content do
  %section#about.default
    %header
      %h1
        What's Flex?

    #flex-ways
      OpenShift Flex manages the resources offered by Amazon Web Services (and others coming soon). There's two ways to get started:

      %ol
        %li
          %p 
            Provide your Amazon EC2 credentials in order to authorize OpenShift Flex to deploy cloud servers on your behalf.
        
        %em OR

        %li#free-flex
          %p#offer
            Take advantage of Red Hat's free trial offer. The free trial includes 30 days or 30 hours (whichever comes first) of free cloud resources from Amazon EC2.

          %p.terms
            The free trial is governed by the terms and conditions agreed to during the registration process for OpenShift.
          
          %p.terms
            Please Remember:
          
          %ul.terms     
            
          
            %li
              OpenShift is in developer preview with no service level agreements.

            %li
              OpenShift should not be used for production purposes.
  
            %li
              At Red Hat's discretion, it may decommission the resources it granted as part of the free trial without notification, explanation, or backup.

            %li
              Users of OpenShift Flex are responsible for making backups of all their data

            %li
              After the expiration of the free trial, the resources and data on them will be deleted

            %li
              To maximize the time of your free trial we recommend that you stop your cluster when not utilizing it
  
    %h2
      Build your Server Cluster and Application Stack
      
    %p
      OpenShift Flex's wizard driven interface makes it easy to provision resources and build integrated application stacks.

    .vid  
      <iframe width="425" height="349" src="//www.youtube.com/embed/CEm-o61tocU" frameborder="0" allowfullscreen></iframe>
    
    %h2
      Deploy, Modify, Rollback and Restart Applications
    
    %p
      OpenShift Flex makes it easy to deploy your application, make modifications to code and components, version your changes and redeploy.

    .vid  
      <iframe width="425" height="349" src="//www.youtube.com/embed/KxX7wUg4zq8" frameborder="0" allowfullscreen></iframe>
        
    %h2
      Monitoring and Auto-Scaling Built-in
    
    %p
      Without the use of agents or scripts, OpenShift Flex gives you end-to-end monitoring straight-out-of-box with configurable auto-scaling that lets you decide when and how to scale your application.
    
    .vid  
      <iframe width="425" height="349" src="//www.youtube.com/embed/CbUQyc7OFlA" frameborder="0" allowfullscreen></iframe>

  %section#videos
    %header
      %h1
        Videos
        
    .product-video 
      %h2 
        OpenShift Flex Product Tour
      %p.video-author.author
        Issac Roth,  PaaS Master - Red Hat
      
      .video-thumb.thumb
        = link_to 'video/OpenShift-Flex-demo' do
          = image_tag "/app/images/video_stills/OpenShift-Flex-demo.png", 
            :title => "OpenShift Flex Product Tour", 
            :alt => "OpenShift Flex Product Tour"
    
      %p.video-description
        This video walks you through the high level functionality of OpenShift Flex, covering provisioning, deploying, monitoring and scaling applications in the cloud.
 
    .product-video 
      %h2
        What are people saying about OpenShift?
      %p.video-author.author
        Developers, ISVs, customers and partners
      
      .video-thumb.thumb
        = link_to "video/OpenShift-Ecosystem" do
          = image_tag "/app/images/video_stills/OpenShift-Ecosystem.png", 
            :title => "Developers, ISVs, customers and partners", 
            :alt => "Developers, ISVs, customers and partners"
        
      %p.video-description
        
        This video shows you what developers, ISVs, customers and partners are saying about Red Hat's exciting new OpenShift PaaS.
      
    .product-video
      %h3 Deploying a Mongo Driven Application on OpenShift Flex
      %p.video-author.author
        David Blado
        
      .video-thumb.thumb
        <iframe width="300" height="200" src="//www.youtube.com/embed/tGOUo3_I8pQ" frameborder="0" allowfullscreen></iframe>
      
      %p.video-description
        This video walks a user through deploying an application on OpenShift Flex that uses MongoDB as its database backend. Complete with performance and log management demo!
      
        .video-meta.meta
          %p.video-length
            3 min, 3 seconds
          %p.video-date.date
            Posted June 21, 2011
      
    .product-video
      %h3 Deploying a Seam Application on OpenShift Flex
      %p.video-author.author
        David Blado
        
      .video-thumb.thumb
        <iframe width="300" height="200" src="//www.youtube.com/embed/axH_XNGhr08" frameborder="0" allowfullscreen></iframe>
      
      %p.video-description
        This video walks a user through deploying a Seam application on OpenShift Flex. Complete with a performance and log management demo!
      
        .video-meta.meta
          %p.video-length
            2 min, 33 seconds
          %p.video-date.date
            Posted June 21, 2011
    
    = link_to 'Watch more videos',  "http://www.redhat.com/openshift/videos", :class => 'more'
  
  -if logged_in?
    %section#quickstart
      %header
        %h1
          Quickstart
    
      %p
        Clicking on the link below will take you to the Flex application where you can start migrating your applications to the cloud.

      = link_to 'Go to Flex', flex_redirect_path, :class => 'more'

site/app/views/product/power.html.haml
-# file: Power product page

- content_for :page_title do
  Power

-# Product navigation
- content_for :product_nav do
  %ul 
    %li
      What's Power?

- content_for :product_content do
  %section#about
    %header
      %h1 
        What is Power?
    
    %p 
      <strong>Coming soon!</strong> OpenShift Power can deploy applications to the cloud that are written to Linux (i.e. written in C, or using many binary components) and anything that builds on Linux. From completely custom architectures to standard n-tier deployments, Power gives you the ultimate flexibility and access at the operating system configuration level. Power can deploy applications which have no web front-end (e.g. trading systems, modeling systems, payment processing, client-server, messaging apps, etc). Power has an image configuration system, a scripting template system, an image library for re-using template, and a way to dynamically define multi-VM architectures that span clouds.