site/config/routes.rb
RedHatCloud::Application.routes.draw do

  scope Rails.configuration.app_scope do

    match 'getting_started/express', :to => redirect('/app/express')
    match 'getting_started/flex', :to => redirect('/app/flex')
    match 'access/express(/:request)', :to => redirect('/app/express')
    match 'access/flex(/:request)', :to => redirect('/app/flex')

    match 'getting_started' => 'getting_started/generic#show'
    match 'getting_started_external/:registration_referrer' => 'getting_started_external#show'
    match 'email_confirm' => 'email_confirm#confirm'
    match 'email_confirm_external/:registration_referrer' => 'email_confirm#confirm_external'
    match 'email_confirm_flex' => 'email_confirm#confirm_flex'
    match 'email_confirm_express' => 'email_confirm#confirm_express'
    match 'express' => 'product#express', :as => 'express'
    match 'flex' => 'product#flex', :as => 'flex'
    match 'express_protected' => 'product#express_protected', :as => 'express_protected'
    match 'flex_protected' => 'product#flex_protected', :as => 'flex_protected'
    match 'power' => 'product#power', :as => 'power'
    match 'flex_redirect' => 'product#flex_redirect', :as => 'flex_redirect'
    match 'about' => 'home#about', :as => 'about'
    match 'twitter_latest_tweet' => 'twitter#latest_tweet'
    match 'twitter_latest_retweets' => 'twitter#latest_retweets'
    match 'partners/join' => 'partner#join', :as=> 'join_partner'

    resource :user,
             :controller => "user",
             :as => "web_users",
             :only => [:new, :create]

    match 'user/new/flex' => 'user#new_flex', :via => [:get]
    match 'user/new/express' => 'user#new_express', :via => [:get]
    get 'user' => 'user#new'
    match 'user/create/external' => 'user#create_external', :via => [:post]

    resource :terms,
             :as => "terms",
             :controller => "terms",
             :path_names => { :new => 'accept' },
             :only => [:new, :create]

    match 'legal/acceptance_terms' => 'terms#acceptance_terms', :as => 'acceptance_terms'

    match 'video/:name' => 'video#show', :as => 'video'

    match 'legal' => 'legal#show'
    match 'legal/site_terms' => 'legal#site_terms'
    match 'legal/services_agreement' => 'legal#services_agreement'
    match 'legal/acceptable_use' => 'legal#acceptable_use'
    match 'legal/openshift_privacy' => 'legal#openshift_privacy'

    resource :login,
             :controller => "login",
             :only => [:show, :create]
    match 'login/error' => 'login#error', :via => [:get]
    match 'login/flex' => 'login#show_flex', :via => [:get]
    match 'login/express' => 'login#show_express', :via => [:get]

    resource :logout,
             :controller => "logout",
             :only => [:show]
    match 'logout/flex' => 'logout#show_flex', :via => [:get]
    match 'logout/express' => 'logout#show_express', :via => [:get]

    resources :partners,
              :controller => "partner",
              :only => [:show, :index]

    resource :express_domain,
             :controller => "express_domain",
             :as => "express_domains",
             :only => [:new, :create]
  
    resource  :express_app,
              :controller => "express_app",
              :as => "express_apps",
              :only => [:new, :create]
    
    get 'express_app/health_check' => 'express_app#health_check'
    
    match 'control_panel' => 'control_panel#index'
    match 'dashboard' => 'control_panel#index', :as => 'dashboard'

    root :to => "home#index"

  end
end

site/app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

site/app/views/layouts/_footer.html.haml
%nav
  %header
    %h1
      Secondary Navigation

  .content
    %ul
      %li
        %header
          %h2
            News
          
        %ul
          %li
            = link_to 'Announcements', 'https://www.redhat.com/openshift/forums/news-and-announcements'
          %li
            = link_to 'Blog', 'https://www.redhat.com/openshift/blogs'
              
          %li
            = link_to 'Twitter', 'http://www.twitter.com/#!/openshift'
        
      %li
        %header
          %h2
            Community
        
        %ul
          %li
            = link_to 'Forum', 'https://www.redhat.com/openshift/forums/'
          %li
            = link_to 'Partner Program', partners_path
          %li
            = link_to 'IRC Channel', 'http://webchat.freenode.net/?randomnick=1&channels=openshift&uio=d4'
          %li
            = link_to 'Feedback', 'mailto:openshift@redhat.com'
        
      %li
        %header
          %h2
            Legalese
        
        %ul
          %li
            = link_to 'Legal', legal_path
          %li
            = link_to 'Privacy Policy', legal_openshift_privacy_path
          %li
            = link_to 'Security', 'https://access.redhat.com/security/team/contact/'
        
      %li
        %header
          %h2
            Help
          
        %ul
          %li
            = link_to 'FAQ', 'http://www.redhat.com/openshift/faq'
          %li
            = link_to 'Contact', 'mailto:openshift@redhat.com'

%section#copyright
  %header
    %h1
      Copyright

  .content
    %p
      Copyright &copy; 2011 Red Hat, Inc.
    
    %img.redhat{ :src => "/app/images/redhat.png", :alt => "Red Hat" }

site/app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

-# Allow views to modify title if desired
%title
  OpenShift by Red Hat
  - if content_for?(:page_title)
    |
    = yield :page_title
  
%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag '/app/javascripts/modernizr.min.js'

= csrf_meta_tag

site/app/views/layouts/_header.html.haml
%hgroup.title
  %h1
    OpenShift
  %h2
    PaaS by Red Hat Cloud

.content
  = link_to root_path do
    = image_tag '/app/images/openshift-logo-white.png', 
               :alt => 'OpenShift Logo',
               :border => '0'
    
  %aside#announcements
    %header
      %h1 OpenShift Announcements
        
    %ul
      %li
        = link_to "http://makara.nurturehq.com/makara/newsletter_signup.html", :class => 'announcement' do
          .title
            Sign up for the OpenShift Newsletter
          .further
            Tricks and Tips, Latest apps, Events and more
      
      %li
        = link_to 'https://twitter.com/#!/openshift', :class => 'announcement' do
          .title
            Follow us on Twitter!
          .further
            @openshift
      
      %li
        = link_to 'mailto:openshift@redhat.com', :class => 'announcement' do
          .title
            Got a cool app? Tell us about it!
          .further
            Drop us a line at openshift@redhat.com <br/> and claim your swag.

%nav
  %header
    %h1
      Main Navigation
  .content
    %ul
      %li.link
        = link_to 'Home', root_path, :class => 'home'
      %li.link
        = link_to 'Cloud Services', express_path, :class => 'services'
      %li.link
        = link_to 'Community', 'https://www.redhat.com/openshift', :class => 'community'
     
      -if session[:login]
        %li.user
          = link_to 'Sign out', logout_path, :class => 'sign_out'
        %li.user
          = link_to "Greetings, #{session[:login]}!", dashboard_path, :class => 'greeting'
          
        
       
      -else
        %li.user
          = link_to 'Sign In', login_path, :class => 'sign_in'
      
= yield :extra_nav if content_for? :extra_nav

site/app/views/layouts/_javascripts.html.haml
= javascript_include_tag '/app/javascripts/jquery.min.js', '/app/javascripts/rails', '/app/javascripts/plugins'
    
-#  Append your own using content_for :javascripts
= yield :javascripts

site/app/views/layouts/_signin_dialog.html.haml
-# Sign in dialog box

#signin.dialog
  %header
    %h1
      Sign in to OpenShift

  %a.sign_up.more{ :href => "#" }
    Need an OpenShift account?

  %form
    %label
      Email
      %input{ :type => "email",
              :placeholder => "Enter your email address",
              :autofocus => "true" }
    
    %label
      Password
      %input{ :type => "password",
              :placeholder => "Enter your password" }
    
    %input.button{ :type => "submit",
                   :value => "Sign in to OpenShift" }



  %a.close_button{ :href => "#",
                   :title => "Close this dialog" }
    %img{ :src => "/app/images/close_button.png" }

site/app/views/layouts/_signup_dialog.html.haml
-# Sign up dialog box
#signup.dialog
  %header
    %h1
      Sign up for OpenShift - it's Easy!
     
  %a.sign_in.more{ :href => "#" }
    Already have an account?
       
  %form
    
    %label
      Email
      %input{ :type => "email", 
              :placeholder => "Enter your email address", 
              :autofocus => true }
    
    %formset.confirm
      %legend Password
      
      %input{ :type => "password",
                :placeholder => "at least 8 characters" }
                
      %input{ :type => "password",
                :placeholder => "please confirm" }
    
    %input.button{ :type => "submit",
                   :value => "Sign me up!" }
  
  %a.close_button{ :href => "#",
                   :title => "Close this dialog" }
    %img{ :src => "/app/images/close_button.png" }

site/app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag '/app/stylesheets/style.css', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

site/app/views/layouts/application.html.haml
- content_for :javascripts do
  = javascript_include_tag '/app/javascripts/script.js'

!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    = render "layouts/head", 
      :stylesheet_partial => "layouts/stylesheets"
  
  %body{ :class => "#{controller.controller_name} #{controller.action_name}" }
    
    %header.universal
      = render "layouts/header", 
        :username => session[:login].nil? ? nil : session[:login]
    
    = content_for?(:sub_layout) ? yield(:sub_layout) : yield
      
    %footer.universal
      = render "layouts/footer"
        
    -# Javascript at the bottom for fast page loading
    = render "layouts/javascripts"
    = render 'shared/omniture_code', :controller => controller.controller_name, :action => controller.action_name, :event => @event ||= ''

  -# Dialog boxes
  = render 'layouts/signin_dialog'
  = render 'layouts/signup_dialog'

site/app/views/layouts/product.html.haml
- content_for :extra_nav do
  %nav.service
    %header
      %h1
        Cloud Services
    .content
      %ul
        %li
          = link_to 'Express', express_path, :class => 'express'
        %li
          = link_to 'Flex', flex_path, :class => 'flex'
        %li
          = link_to 'Power', power_path, :class => 'power'

- content_for :sub_layout do
  %section.main
    %header
      %h1
        = yield :page_title if content_for? :page_title
    
    .content
      %nav
        %header
          %h2 
            Cloud Service Navigation
        
        = yield :product_nav if content_for? :product_nav
      
      .content
        = yield :product_content if content_for? :product_content
            

= render :file => 'layouts/application'